# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm i
      

    - name: Run Tests
      run: npm run test:unit
    

    - name: Display Softuni UserName
      run: echo "SoftUni Username = PowerCell12"


  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm i & npx playwright install  

    - name: start front-end
      run: npm start & 

    - name: Run Tests
      run: npm run test:ui


  start-render:
      needs: [unit-tests]
      
      runs-on: ubuntu-latest
      
      steps:
      
        - name: Deploy Project
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
  
